# Generated by Django 5.1.4 on 2026-02-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='modifiers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
