# Generated by Django 5.1.4 on 2026-02-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='available_modifiers',
            field=models.JSONField(blank=True, default=dict, help_text='List of available modifiers'),
        ),
    ]
